//
import type { Metadata } from "next";
import { Toaster } from "sonner";
import { Inter } from "next/font/google";

// @/
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import { ThemeProvider } from "@/components/theme-provider";

// ./
import "./globals.css";

// Font
const inter = Inter({ subsets: ["latin"] });

// MetaData
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

// !_____________________________________________________________________________
export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ClerkProvider
            appearance={{
                baseTheme: dark,
            }}
        >
            <html lang="en">
                <body className={inter.className}>
                    <ThemeProvider
                        attribute="class"
                        forcedTheme="dark"
                        storageKey="PlayHub-Theme"
                    >
                        <Toaster theme={"light"} position="bottom-center" />
                        {children}
                    </ThemeProvider>
                </body>
            </html>
        </ClerkProvider>
    );
}
